-- DEPT表の作成
CREATE TABLE dept (
    deptno NUMBER PRIMARY KEY,
    dname VARCHAR2(10),
    loc VARCHAR2(12)
);
-- DEPT表にデータ追加
INSERT INTO dept VALUES(20, 'SALES1', 'NEW YORK');
INSERT INTO dept VALUES(30, 'SALES2', 'TRONT');
INSERT INTO dept VALUES(10, 'OPERATIONS', 'NEW YORK');
INSERT INTO dept VALUES(90, 'SPECIAL', 'HAWAII');

-- EMP表の作成
CREATE TABLE emp (
    empno NUMBER PRIMARY KEY,
    ename VARCHAR2(8),
    job VARCHAR2(10),
    sal NUMBER,
    comm_pct NUMBER(2,2),
    bonus NUMBER,
    deptno NUMBER
);
-- EMP表にデータ追加
INSERT INTO emp VALUES(1001, 'Tom', 'SALESMAN', 720, 0.50, NULL, 20);
INSERT INTO emp VALUES(1002, 'Abe', 'ASSISTANT', 600, NULL, 1000, 20);
INSERT INTO emp VALUES(1003, 'Clark', 'SALESMAN', 720, NULL, 500, 20);
INSERT INTO emp VALUES(1004, 'Blake', 'ASSISTANT', 720, NULL, 720, 10);
INSERT INTO emp VALUES(1005, 'Zakk', 'MANAGER', 900, NULL, 2000, 20);
INSERT INTO emp VALUES(1006, 'Bob', 'SALESMAN', 510, 0.25, NULL, 30);

-- COMMIT
COMMIT;